---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Set up filesystem with '...'
2. Mount USB disk for the backup with filesystem '....'
3. Run _backupbrace_
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Configuration**
If applicable, add your configuration file to help explain your problem.

**Log output**
If applicable, add relevant parts of the log file to help explain your problem.

**Operating environment (please complete the following information):**
 - Linux distribution: [e.g. OpenSuse, Fedora, Ubuntu]
 - Distribution version [e.g. 15.2, 23]
 - Python version [e.g. 3.6.12]

**Additional context**
Add any other context about the problem here.
